In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
print(os.listdir("../input"))

['Housing Price data set.csv']


In [2]:
df = pd.read_csv('../input/Housing Price data set.csv')
df_top = df.head()
df_tops = df_top.columns
#print(df_tops)
x_features = df_tops[2:]
#x_features
x_df = df[x_features]
y_df = df['price']

In [3]:
x_df = x_df.replace({'yes': 1, 'no': 0})
print(x_df.min())
print()
print(x_df.max())

lotsize     1650
bedrooms       1
bathrms        1
stories        1
driveway       0
recroom        0
fullbase       0
gashw          0
airco          0
garagepl       0
prefarea       0
dtype: int64

lotsize     16200
bedrooms        6
bathrms         4
stories         4
driveway        1
recroom         1
fullbase        1
gashw           1
airco           1
garagepl        3
prefarea        1
dtype: int64


In [4]:
x_df = (x_df - np.mean(x_df))/(x_df.max()-x_df.min())
x_df.insert( 0 ,"b",1)
x_df

b   lotsize  bedrooms    ...       airco  garagepl  prefarea
0    1  0.048092   0.00696    ...    -0.31685  0.102564 -0.234432
1    1 -0.079056  -0.19304    ...    -0.31685 -0.230769 -0.234432
2    1 -0.143661   0.00696    ...    -0.31685 -0.230769 -0.234432
3    1  0.103075   0.00696    ...    -0.31685 -0.230769 -0.234432
4    1  0.083143  -0.19304    ...    -0.31685 -0.230769 -0.234432
5    1 -0.068059   0.00696    ...     0.68315 -0.230769 -0.234432
6    1 -0.087303   0.00696    ...    -0.31685  0.435897 -0.234432
7    1 -0.068059   0.00696    ...    -0.31685 -0.230769 -0.234432
8    1 -0.024073   0.00696    ...    -0.31685 -0.230769 -0.234432
9    1  0.024037   0.00696    ...     0.68315  0.102564 -0.234432
10   1  0.140875   0.00696    ...     0.68315  0.769231 -0.234432
11   1 -0.147785  -0.19304    ...    -0.31685 -0.230769 -0.234432
12   1 -0.237132   0.00696    ...    -0.31685 -0.230769 -0.234432
13   1 -0.156032   0.00696    ...    -0.31685 -0.230769 -0.234432
14   1 -0.106547  -0.19304    ...    -0.31685 -0.230769 -0.234432
15   1 -0.135070  -0.19304    ...     0.68315 -0.230769 -0.234432
16   1 -0.127166   0.00696    ...    -0.31685  0.102564 -0.234432
17   1  0.003418   0.20696    ...    -0.31685 -0.230769 -0.234432
18   1 -0.116857  -0.39304    ...    -0.31685 -0.230769 -0.234432
19   1 -0.080018  -0.19304    ...    -0.31685  0.102564 -0.234432
20   1 -0.025104   0.00696    ...     0.68315  0.102564 -0.234432
21   1 -0.044005   0.20696    ...    -0.31685 -0.230769 -0.234432
22   1 -0.079056   0.00696    ...     0.68315 -0.230769 -0.234432
23   1 -0.083592  -0.19304    ...    -0.31685 -0.230769 -0.234432
24   1 -0.013077  -0.19304    ...    -0.31685 -0.230769 -0.234432
25   1 -0.147785  -0.19304    ...    -0.31685 -0.230769 -0.234432
26   1 -0.092802  -0.19304    ...    -0.31685 -0.230769 -0.234432
27   1 -0.013077  -0.19304    ...     0.68315 -0.230769 -0.234432
28   1 -0.147785   0.00696    ...     0.68315 -0.230769 -0.234432
29   1 -0.044692   0.00696    ...     0.68315 -0.230769 -0.234432
..  ..       ...       ...    ...         ...       ...       ...
516  1  0.058401   0.00696    ...     0.68315 -0.230769 -0.234432
517  1  0.058401   0.20696    ...     0.68315 -0.230769 -0.234432
518  1  0.074896   0.20696    ...     0.68315  0.102564 -0.234432
519  1  0.058401   0.00696    ...    -0.31685  0.102564 -0.234432
520  1  0.173865   0.20696    ...     0.68315  0.102564 -0.234432
521  1  0.058401   0.20696    ...     0.68315  0.102564 -0.234432
522  1  0.058401   0.20696    ...     0.68315  0.102564 -0.234432
523  1  0.058401   0.20696    ...    -0.31685  0.435897 -0.234432
524  1  0.058401   0.20696    ...     0.68315  0.102564 -0.234432
525  1  0.159776   0.00696    ...     0.68315  0.435897 -0.234432
526  1 -0.000018   0.00696    ...     0.68315  0.435897 -0.234432
527  1  0.080738   0.00696    ...     0.68315  0.102564 -0.234432
528  1  0.058401   0.00696    ...     0.68315  0.102564 -0.234432
529  1  0.058401   0.00696    ...     0.68315 -0.230769 -0.234432
530  1  0.058401   0.00696    ...     0.68315  0.435897 -0.234432
531  1  0.127130   0.00696    ...     0.68315  0.435897 -0.234432
532  1  0.532628   0.00696    ...    -0.31685  0.435897 -0.234432
533  1  0.174277   0.00696    ...    -0.31685 -0.230769 -0.234432
534  1 -0.010328   0.00696    ...     0.68315 -0.230769 -0.234432
535  1  0.044655   0.00696    ...     0.68315 -0.230769 -0.234432
536  1  0.058401   0.00696    ...     0.68315 -0.230769 -0.234432
537  1 -0.024073   0.00696    ...     0.68315 -0.230769 -0.234432
538  1  0.092765   0.00696    ...     0.68315 -0.230769 -0.234432
539  1  0.149123   0.20696    ...    -0.31685 -0.230769 -0.234432
540  1  0.094483   0.00696    ...    -0.31685  0.102564 -0.234432
541  1 -0.024073   0.00696    ...     0.68315 -0.230769 -0.234432
542  1  0.058401   0.00696    ...     0.68315 -0.230769 -0.234432
543  1  0.058401   0.00696    ...     0.68315  0.102564 -0.234432
544  1  0.058401   0.00696    ...     0.68315

In [5]:
m = x_df.shape[0] # Training Examples 
n = x_df.shape[1] # Number of features

In [6]:
lambdaa = 50
I = np.identity(n)
I[0][0] = 0

In [7]:
I

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [8]:

def NormalEquationRegularization(x_df,y_df):
    "Linear Regression using Normal Equation"
    transX = x_df.transpose()
    first = np.dot(transX,x_df)
    second = lambdaa*I
    first = first + second
    try:
        first = np.linalg.inv(first)
    except np.linalg.LinAlgError:
        print("X is not invertible")
    second = np.dot(transX,y_df)
    second = second.reshape(second.size, 1)
    return np.dot(first,second)

In [9]:
weights = NormalEquationRegularization(x_df,y_df)
weights

array([[68121.5970696 ],
       [11657.51996144],
       [ 6586.81623119],
       [12972.78783269],
       [12961.82836358],
       [ 7457.8505578 ],
       [ 5572.85505785],
       [ 4488.37788283],
       [ 4733.3941616 ],
       [12933.78516711],
       [11298.50651238],
       [ 8921.66375285]])

In [10]:
x_df 

b   lotsize  bedrooms    ...       airco  garagepl  prefarea
0    1  0.048092   0.00696    ...    -0.31685  0.102564 -0.234432
1    1 -0.079056  -0.19304    ...    -0.31685 -0.230769 -0.234432
2    1 -0.143661   0.00696    ...    -0.31685 -0.230769 -0.234432
3    1  0.103075   0.00696    ...    -0.31685 -0.230769 -0.234432
4    1  0.083143  -0.19304    ...    -0.31685 -0.230769 -0.234432
5    1 -0.068059   0.00696    ...     0.68315 -0.230769 -0.234432
6    1 -0.087303   0.00696    ...    -0.31685  0.435897 -0.234432
7    1 -0.068059   0.00696    ...    -0.31685 -0.230769 -0.234432
8    1 -0.024073   0.00696    ...    -0.31685 -0.230769 -0.234432
9    1  0.024037   0.00696    ...     0.68315  0.102564 -0.234432
10   1  0.140875   0.00696    ...     0.68315  0.769231 -0.234432
11   1 -0.147785  -0.19304    ...    -0.31685 -0.230769 -0.234432
12   1 -0.237132   0.00696    ...    -0.31685 -0.230769 -0.234432
13   1 -0.156032   0.00696    ...    -0.31685 -0.230769 -0.234432
14   1 -0.106547  -0.19304    ...    -0.31685 -0.230769 -0.234432
15   1 -0.135070  -0.19304    ...     0.68315 -0.230769 -0.234432
16   1 -0.127166   0.00696    ...    -0.31685  0.102564 -0.234432
17   1  0.003418   0.20696    ...    -0.31685 -0.230769 -0.234432
18   1 -0.116857  -0.39304    ...    -0.31685 -0.230769 -0.234432
19   1 -0.080018  -0.19304    ...    -0.31685  0.102564 -0.234432
20   1 -0.025104   0.00696    ...     0.68315  0.102564 -0.234432
21   1 -0.044005   0.20696    ...    -0.31685 -0.230769 -0.234432
22   1 -0.079056   0.00696    ...     0.68315 -0.230769 -0.234432
23   1 -0.083592  -0.19304    ...    -0.31685 -0.230769 -0.234432
24   1 -0.013077  -0.19304    ...    -0.31685 -0.230769 -0.234432
25   1 -0.147785  -0.19304    ...    -0.31685 -0.230769 -0.234432
26   1 -0.092802  -0.19304    ...    -0.31685 -0.230769 -0.234432
27   1 -0.013077  -0.19304    ...     0.68315 -0.230769 -0.234432
28   1 -0.147785   0.00696    ...     0.68315 -0.230769 -0.234432
29   1 -0.044692   0.00696    ...     0.68315 -0.230769 -0.234432
..  ..       ...       ...    ...         ...       ...       ...
516  1  0.058401   0.00696    ...     0.68315 -0.230769 -0.234432
517  1  0.058401   0.20696    ...     0.68315 -0.230769 -0.234432
518  1  0.074896   0.20696    ...     0.68315  0.102564 -0.234432
519  1  0.058401   0.00696    ...    -0.31685  0.102564 -0.234432
520  1  0.173865   0.20696    ...     0.68315  0.102564 -0.234432
521  1  0.058401   0.20696    ...     0.68315  0.102564 -0.234432
522  1  0.058401   0.20696    ...     0.68315  0.102564 -0.234432
523  1  0.058401   0.20696    ...    -0.31685  0.435897 -0.234432
524  1  0.058401   0.20696    ...     0.68315  0.102564 -0.234432
525  1  0.159776   0.00696    ...     0.68315  0.435897 -0.234432
526  1 -0.000018   0.00696    ...     0.68315  0.435897 -0.234432
527  1  0.080738   0.00696    ...     0.68315  0.102564 -0.234432
528  1  0.058401   0.00696    ...     0.68315  0.102564 -0.234432
529  1  0.058401   0.00696    ...     0.68315 -0.230769 -0.234432
530  1  0.058401   0.00696    ...     0.68315  0.435897 -0.234432
531  1  0.127130   0.00696    ...     0.68315  0.435897 -0.234432
532  1  0.532628   0.00696    ...    -0.31685  0.435897 -0.234432
533  1  0.174277   0.00696    ...    -0.31685 -0.230769 -0.234432
534  1 -0.010328   0.00696    ...     0.68315 -0.230769 -0.234432
535  1  0.044655   0.00696    ...     0.68315 -0.230769 -0.234432
536  1  0.058401   0.00696    ...     0.68315 -0.230769 -0.234432
537  1 -0.024073   0.00696    ...     0.68315 -0.230769 -0.234432
538  1  0.092765   0.00696    ...     0.68315 -0.230769 -0.234432
539  1  0.149123   0.20696    ...    -0.31685 -0.230769 -0.234432
540  1  0.094483   0.00696    ...    -0.31685  0.102564 -0.234432
541  1 -0.024073   0.00696    ...     0.68315 -0.230769 -0.234432
542  1  0.058401   0.00696    ...     0.68315 -0.230769 -0.234432
543  1  0.058401   0.00696    ...     0.68315  0.102564 -0.234432
544  1  0.058401   0.00696    ...     0.68315

In [11]:
y_df = y_df.values.reshape(y_df.size,1)
y_df.shape

(546, 1)

In [12]:
predictions = np.dot(x_df,weights)

In [13]:
simple_error = y_df - predictions
print(simple_error)

[[-2.40559165e+04]
 [-1.21811694e+04]
 [-1.74540078e+03]
 [-3.51518809e+03]
 [ 8.42798886e+03]
 [-9.12174342e+03]
 [-6.56797579e+03]
 [ 8.23205577e+03]
 [ 2.10992711e+04]
 [-4.25923888e+03]
 [ 2.39268198e+03]
 [-1.19221147e+04]
 [-2.74763726e+04]
 [-7.64333348e+03]
 [-1.33606878e+04]
 [-2.50619732e+04]
 [-1.15666175e+04]
 [-2.21685598e+04]
 [-3.92314390e+03]
 [-1.63637664e+04]
 [-3.52092743e+04]
 [-9.57759953e+02]
 [-3.13529273e+04]
 [-1.26282899e+04]
 [-9.45032537e+03]
 [-1.19005747e+04]
 [-7.02092859e+03]
 [-2.48724884e+04]
 [-1.21732631e+04]
 [-2.47535293e+04]
 [-2.31109467e+03]
 [-2.97020261e+04]
 [-1.68116941e+03]
 [ 4.18228529e+02]
 [ 4.10737941e+03]
 [-1.05478943e+04]
 [ 6.50481417e+03]
 [-1.18315550e+04]
 [-1.54857658e+03]
 [ 3.14506416e+03]
 [ 5.89678706e+03]
 [-4.15793130e+03]
 [ 2.00845552e+04]
 [ 1.31957536e+04]
 [-1.53993706e+04]
 [-7.87545385e+03]
 [-1.45416290e+03]
 [-5.13219580e+03]
 [-7.26842021e+03]
 [-9.98359433e+02]
 [-9.31969657e+03]
 [ 6.57345636e+03]
 [-1.1774690

In [14]:
squared_error = simple_error**2
print(squared_error)

[[5.78687117e+08]
 [1.48380888e+08]
 [3.04642389e+06]
 [1.23565473e+07]
 [7.10309963e+07]
 [8.32062031e+07]
 [4.31383059e+07]
 [6.77667423e+07]
 [4.45179241e+08]
 [1.81411158e+07]
 [5.72492707e+06]
 [1.42136820e+08]
 [7.54951053e+08]
 [5.84205467e+07]
 [1.78507977e+08]
 [6.28102502e+08]
 [1.33786641e+08]
 [4.91445042e+08]
 [1.53910580e+07]
 [2.67772850e+08]
 [1.23969300e+09]
 [9.17304127e+05]
 [9.83006049e+08]
 [1.59473707e+08]
 [8.93086495e+07]
 [1.41623679e+08]
 [4.92934382e+07]
 [6.18640680e+08]
 [1.48188336e+08]
 [6.12737215e+08]
 [5.34115860e+06]
 [8.82210357e+08]
 [2.82633059e+06]
 [1.74915102e+05]
 [1.68705656e+07]
 [1.11258074e+08]
 [4.23126074e+07]
 [1.39985694e+08]
 [2.39808942e+06]
 [9.89142855e+06]
 [3.47720976e+07]
 [1.72883927e+07]
 [4.03389356e+08]
 [1.74127914e+08]
 [2.37140616e+08]
 [6.20227734e+07]
 [2.11458973e+06]
 [2.63394338e+07]
 [5.28299324e+07]
 [9.96721557e+05]
 [8.68567442e+07]
 [4.32103285e+07]
 [1.38643339e+08]
 [6.58480190e+08]
 [6.14357015e+08]
 [6.439775

In [15]:
squared_error_value = sum(squared_error)/len(squared_error)
root_mean_squared_error = squared_error_value ** (1/2)

In [16]:
print('root_mean_squared_error' + str(root_mean_squared_error))

root_mean_squared_error[18022.61818566]
