In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import mean_squared_error
print(os.listdir("../input"))
# Any results you write to the current directory are saved as output.

['Housing Price data set.csv']


In [2]:
df = pd.read_csv('../input/Housing Price data set.csv')
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 13 columns):
Unnamed: 0    546 non-null int64
price         546 non-null float64
lotsize       546 non-null int64
bedrooms      546 non-null int64
bathrms       546 non-null int64
stories       546 non-null int64
driveway      546 non-null object
recroom       546 non-null object
fullbase      546 non-null object
gashw         546 non-null object
airco         546 non-null object
garagepl      546 non-null int64
prefarea      546 non-null object
dtypes: float64(1), int64(6), object(6)
memory usage: 55.5+ KB


In [3]:
df = df.replace({'yes': 1, 'no': 0})

In [4]:
df.head()

Unnamed: 0    price  lotsize    ...     airco  garagepl  prefarea
0           1  42000.0     5850    ...         0         1         0
1           2  38500.0     4000    ...         0         0         0
2           3  49500.0     3060    ...         0         0         0
3           4  60500.0     6650    ...         0         0         0
4           5  61000.0     6360    ...         0         0         0

[5 rows x 13 columns]

In [5]:
df.columns

Index(['Unnamed: 0', 'price', 'lotsize', 'bedrooms', 'bathrms', 'stories',
       'driveway', 'recroom', 'fullbase', 'gashw', 'airco', 'garagepl',
       'prefarea'],
      dtype='object')

In [6]:
x_features = ['lotsize', 'bedrooms', 'bathrms', 'stories','driveway', 'recroom', 'fullbase', 'gashw', 'airco', 'garagepl','prefarea']

In [7]:
df.head()

Unnamed: 0    price  lotsize    ...     airco  garagepl  prefarea
0           1  42000.0     5850    ...         0         1         0
1           2  38500.0     4000    ...         0         0         0
2           3  49500.0     3060    ...         0         0         0
3           4  60500.0     6650    ...         0         0         0
4           5  61000.0     6360    ...         0         0         0

[5 rows x 13 columns]

In [8]:
x_df = df[x_features]

In [9]:
x_df.head()

lotsize  bedrooms  bathrms    ...     airco  garagepl  prefarea
0     5850         3        1    ...         0         1         0
1     4000         2        1    ...         0         0         0
2     3060         3        1    ...         0         0         0
3     6650         3        1    ...         0         0         0
4     6360         2        1    ...         0         0         0

[5 rows x 11 columns]

In [10]:
y_df = df['price']
#y_df.head()
x_df.head()

lotsize  bedrooms  bathrms    ...     airco  garagepl  prefarea
0     5850         3        1    ...         0         1         0
1     4000         2        1    ...         0         0         0
2     3060         3        1    ...         0         0         0
3     6650         3        1    ...         0         0         0
4     6360         2        1    ...         0         0         0

[5 rows x 11 columns]

In [11]:
X_train, X_test, Y_train, Y_test = tts(x_df, y_df, test_size = 0.4, random_state = 5)

In [12]:
m = len(Y_train)
alpha = 0.1
num_iterations = 1000
weights = np.zeros((12,1))

In [13]:
X_train = (X_train - np.mean(X_train))/np.std(X_train)
X_test = (X_test - np.mean(X_test))/np.std(X_test)
Y_train = Y_train[:,np.newaxis]
Y_test = Y_test[:,np.newaxis]

In [14]:
X_train = X_train.assign(b=1)
X_test = X_test.assign(b=1)
X_test.head()

lotsize  bedrooms   bathrms   stories ...     airco  garagepl  prefarea  b
288 -0.774772 -1.412189 -0.560885 -1.007417 ... -0.656790  0.411302 -0.614295  1
526  0.024462 -0.031522  1.452785  2.318579 ...  1.522558  1.566111 -0.614295  1
496 -0.265763 -0.031522 -0.560885 -1.007417 ... -0.656790 -0.743507 -0.614295  1
483 -0.489013 -1.412189 -0.560885 -1.007417 ... -0.656790 -0.743507  1.627882  1
409  0.671886 -0.031522  1.452785  1.209913 ...  1.522558 -0.743507  1.627882  1

[5 rows x 12 columns]

In [15]:
Y_train

array([[ 56000.],
       [ 60500.],
       [ 45000.],
       [ 90000.],
       [ 76000.],
       [ 48000.],
       [112500.],
       [106000.],
       [ 82000.],
       [ 85000.],
       [ 43500.],
       [110000.],
       [ 28000.],
       [ 79500.],
       [ 35000.],
       [ 47000.],
       [ 49000.],
       [ 85000.],
       [127000.],
       [ 27000.],
       [ 62900.],
       [ 37000.],
       [ 63900.],
       [120000.],
       [ 52000.],
       [ 45000.],
       [115442.],
       [ 44000.],
       [ 70000.],
       [ 50000.],
       [ 64500.],
       [ 48500.],
       [ 58550.],
       [ 42000.],
       [130000.],
       [ 75000.],
       [ 58000.],
       [ 65500.],
       [116000.],
       [ 96500.],
       [ 35500.],
       [ 46000.],
       [ 35000.],
       [ 66000.],
       [ 56000.],
       [ 72000.],
       [ 58000.],
       [ 45000.],
       [ 87500.],
       [ 60000.],
       [ 58500.],
       [ 43000.],
       [163000.],
       [140000.],
       [ 41000.],
       [ 5

In [16]:
X_train.head()

lotsize  bedrooms   bathrms   stories ...     airco  garagepl  prefarea  b
469 -1.438539  1.445804  1.404848 -0.884532 ... -0.697398 -0.847359  1.951621  1
3    0.691748  0.098858 -0.575261  0.310683 ... -0.697398 -0.847359 -0.512395  1
283  0.739035 -1.248087 -0.575261 -0.884532 ... -0.697398 -0.847359 -0.512395  1
10   0.951827  0.098858  1.404848 -0.884532 ...  1.433902  2.660062 -0.512395  1
401  1.235550  0.098858 -0.575261 -0.884532 ...  1.433902  1.490922  1.951621  1

[5 rows x 12 columns]

In [17]:
Y_test

array([[ 30000.],
       [105000.],
       [ 60000.],
       [ 51500.],
       [ 89900.],
       [ 64000.],
       [ 85000.],
       [ 62500.],
       [ 78500.],
       [ 44555.],
       [ 46500.],
       [145000.],
       [124000.],
       [ 46500.],
       [ 70500.],
       [ 49900.],
       [ 88500.],
       [ 40500.],
       [120000.],
       [ 66500.],
       [ 60500.],
       [ 50000.],
       [105000.],
       [ 95000.],
       [ 64000.],
       [120900.],
       [ 42000.],
       [ 72000.],
       [ 88500.],
       [ 64000.],
       [ 68500.],
       [ 58500.],
       [ 58500.],
       [ 82000.],
       [ 60000.],
       [ 25245.],
       [ 71500.],
       [ 57000.],
       [ 34400.],
       [ 60000.],
       [ 52900.],
       [ 70000.],
       [ 68000.],
       [ 96000.],
       [ 79000.],
       [ 61100.],
       [ 52000.],
       [ 88000.],
       [ 65000.],
       [ 64500.],
       [ 69000.],
       [ 55000.],
       [ 85000.],
       [ 82000.],
       [ 95500.],
       [ 4

In [18]:
def GDM(x, y, weights, alpha, iterations):
    m = len(y)
    print(x.shape)
    print(y.shape)
    print(weights.shape)
    for _ in range(iterations):
        temp = np.dot(x, weights) - y
        temp = np.dot(x.T, temp)
        weights = weights - (alpha/m) * temp
    return weights

In [19]:
weights = GDM(X_train, Y_train, weights, alpha, num_iterations)

(327, 12)
(327, 1)
(12, 1)


In [20]:
weights.shape

(12, 1)

In [21]:
def GradientDescent_predict(x, weights):
    return np.dot(x, weights)

In [22]:
weights

array([[ 7967.63971777],
       [ 2289.80848238],
       [ 7129.99835101],
       [ 5078.4285851 ],
       [ 2377.51626914],
       [ 1098.64555456],
       [ 3065.25646245],
       [ 2641.61332499],
       [ 5755.81790824],
       [ 4532.02008488],
       [ 4384.20910519],
       [68590.95412844]])

In [23]:
GradientDescent_predict(X_train.iloc[0],weights)

array([70668.14268291])

In [24]:
Y_Predicted = [GradientDescent_predict(x,weights) for x in X_test.values]

In [25]:
mean_squared_error(Y_test, Y_Predicted)

161123024.98146525